
# Set the initial wallpaper for your monitor (eDP-1)
# This ensures you have a background immediately upon login
wallpaper { 
  monitor = eDP-1
  path = /home/saumya/images/wallpapers/cameron-venti-big-fish.jpg
  fit_mode = cover
}

# If you have a second monitor, set it here so it stays static
# wallpaper = HDMI-A-1,/path/to/static_image.jpg

# Enable splash text (optional)
splash = false

wallpaper {
    monitor = HDMI-A-1
    path = /home/saumya/images/wallpapers/pond_shed.png
    fit_mode = cover
}
